# Generated by Django 6.0.7 on 2026-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
